version: "3"
services:
    front:
        build:
            context: ./front
        ports:
            - "3000:3000"
    fachada:
        build:
            context: ./fachada/
        ports:
            - "8082:8082"
        environment:
            ACESSO_URL: "http://acesso:5000"
            CLIENTE_URL: "http://cliente:3000"
    acesso:
        build:
            context: ./controle-acesso
        restart: always
        environment:
            DATABASE_HOST: "acesso_db"
            DATABASE_PORT: "5432"
            SECRET_KEY: "secret_docker"
        ports:
            - "5000:5000"
        depends_on:
        - acesso_db
    cliente:
        build:
            context: ./controle-cliente
        restart: always
        environment:
            DATABASE_HOST: "cliente_db"
            DATABASE_PORT: "5432"
            ACESSO_HOST: "acesso"
            ACESSO_PORT: "5000"
        command: bash -c "bundle exec rails s -b 0.0.0.0"
        ports:
            - "4000:3000"
        depends_on:
        - cliente_db
        - acesso
    acesso_db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "acesso"
    cliente_db:
        image: postgres
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "cliente"
        ports:
        - "15433:5432"