version: "3"
services:
    fachada:
        build:
            context: ./fachada/
        ports:
            - "8080:8080"
    acesso:
        build:
            context: ./controle-acesso
        ports:
          - "5000:5000"
    cliente:
        build:
            context: ./controle-cliente
        command: bash -c "bundle exec rails s"
        ports:
            - "4000:3000"
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "acesso"
        ports:
        - "15432:5432"
    cliente_db:
        image: postgres
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "cliente"
        ports:
        - "15433:5432"