acesso:
  url: "${ACESSO_URL:http://localhost:5000}"
server:
  port: 8082
spring:
    application:
      name: gateway
    cloud:
        gateway:
            default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            routes:
                - id: controle-acesso
                  uri: ${ACESSO_URL:http://localhost:5000}/login
                  predicates:
                  - Path=/login
                - id: controle-cliente
                  uri: ${CLIENTE_URL:http://localhost:4000}/cadastrar
                  predicates:
                  - Path=/cadastrar
                - id: controle-cliente
                  uri: ${CLIENTE_URL:http://localhost:4000}/cartoes/cadastrar
                  predicates:
                  - Path=/cartoes/cadastrar
                  filters:
                  - AcessoFilterFactory
                - id: controle-cliente
                  uri: ${CLIENTE_URL:http://localhost:4000}/cartoes
                  predicates:
                  - Path=/cartoes
                  filters:
                  - AcessoFilterFactory
                - id: controle-cliente
                  uri: ${CLIENTE_URL:http://localhost:4000}/enderecos/cadastrar
                  predicates:
                  - Path=/enderecos/cadastrar
                  filters:
                  - AcessoFilterFactory
                - id: controle-cliente
                  uri: ${CLIENTE_URL:http://localhost:4000}/enderecos
                  predicates:
                  - Path=/enderecos
                  filters:
                  - AcessoFilterFactory
            globalcors:
              corsConfigurations:
                '[/**]':
                  allowedOrigins: "*"
                  allowedHeaders: "*"
                  allowedMethods: "*"