acesso:
  url: http://localhost:5000/verificar
server:
    port: 8082
spring:
    application:
      name: gateway
    cloud:
        gateway:
            default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            routes:
                - id: controle-acesso
                  uri: http://localhost:5000/login
                  predicates:
                  - Path=/login
                - id: controle-cliente
                  uri: http://localhost:4000/cadastrar
                  predicates:
                  - Path=/cadastrar
                - id: controle-cliente
                  uri: http://localhost:4000/cartoes/cadastrar
                  predicates:
                  - Path=/cartoes/cadastrar
                  filters:
                  - AcessoFilterFactory
                - id: controle-acesso
                  uri: http://localhost:5000/
                  predicates:
                  - Path=/
                  filters:
                  - AcessoFilterFactory
            globalcors:
              corsConfigurations:
                '[/**]':
                  allowedOrigins: "*"
                  allowedHeaders: "*"
                  allowedMethods: "*"