version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "acesso"
    ports:
      - "15432:5432"
  # server:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #   restart: always
  #   environment:
  #     DB_URL: 'postgresql://postgres:password@db:5432/postgres'
  #   ports:
  #     - "5000:5000"
